server:
  port: ${PORT:8082}

spring:
  application:
    name: order-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Crea las tablas autom치ticamente
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
# Perfil para Docker
#spring:
#  config:
#    activate:
#      on-profile: docker
#
#  jpa:
#    show-sql: false  # En Docker mejor sin logs

---
# Perfil para producci칩n
spring:
  config:
    activate:
      on-profile: production

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate  # M치s seguro en producci칩n
#  sql:
#    init:
#      mode: always # Asegura que data.sql se ejecute
#      data-locations: classpath:data.sql